drop table endereco if exists;
drop table aluno if exists;
create table aluno (
	matricula bigint generated by default as identity, 
	cpf varchar(255), 
	idade integer not null, 
	nome varchar(255), 
	primary key (matricula)
);
create table endereco (
	id bigint generated by default as identity, 
	bairro varchar(255), 
	cep integer not null, 
	cidade varchar(255), 
	complemento varchar(255), 
	estado varchar(255), 
	logradouro varchar(255), 
	numero varchar(255), 
	aluno_id bigint, 
	primary key (id)
);
alter table endereco add constraint aluno_fk foreign key (aluno_id) references aluno;